# Generated by Django 6.0.5 on 2026-06-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmManager", "0012_datacollector_datacollectorsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacollectorsubmission",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="FarmManager.datacollector",
            ),
        ),
    ]
